### ISSUE TITLE
Invalid front matter error - on a previously working Metalsmith build

### ISSUE THREAD

**Issue by seffw** [metalsmith/metalsmith#173] opened 2015-09-25 09:18 UTC
Hoping others here might have had this and solved it.

Came back (or was trying to) to Metalsmith using a previously working site and build.js, on a new machine (both Windows) wwith latest versions of Metalsmith and all plugins.

The 'node build' now errors with 'Invalid front matter' on each .md file. The front matter is ok (and unchanged from the working site).

Anyone know what has changed in Metalsmith that might cause this? Apologies for the general nature of this, it jjust seems likely this willl have happened to others after a recent(ish) update.

**Comment by Ajedi32** [comment] 2015-09-25 13:15
Are your line endings messed up perhaps? I can't imagine what might have changed to cause something like that.

**Comment by woodyrew** [comment] 2015-09-25 13:16
Hi @simplyeffectiveweb, assuming it works on version 2.0.1. I would expect @Ajedi32 will be able to help.

**Comment by Ajedi32** [comment] 2015-09-25 14:03
Basically nothing's changed since 2.0.1. The one and only merged PR that changed behavior between those two revisions only affects the Metalsmith CLI, and only if you have `frontmatter: false` in your metalsmith.json file: https://github.com/segmentio/metalsmith/compare/2.0.1...master

**Comment by simplyeffectiveweb** [comment] 2015-09-25 14:53
Thanks for the replies.

It's a mystery for me then.. It was just a straight copy of a site folder (as in the src, templates, etc) from metalsmith a year ago to a new install nnow (with the same plugins installed).

I don't know where to start with the front matter error. The front matter is just 1 line:
---
title: about
---

No spaces are after the lines. Tried with and without "" just in case. I am sure the error is about something else. I've just copied the folder back into the original metalsmith install (on prev laptop, not updated) and it works fine.  So something must have changed with Metalsmith or from what you've said, a plugin. I'm using: 

var markdown = require('metalsmith-markdown');
var templates = require('metalsmith-templates');
var Handlebars = require('handlebars');
var fs = require('fs');
var collections = require('metalsmith-collections');
var permalinks  = require('metalsmith-permalinks');
var sass = require('metalsmith-sass');

var watch = require('metalsmith-watch');
	
var connect = require('connect');
var path = require('path');
var static = require('serve-static');

I know metalsmiith-templates is deprecated but as I understand it still works.

**Comment by Ajedi32** [comment] 2015-09-25 15:08
A year ago this project was all the way back in v1.0.x, so there's plenty of potential for changes between versions there. Your frontmatter does look fine though, so I don't really why there'd be errors.

Let's try doing some basic debugging here to find out where the problem is: If you replace all your markdown files with a new file containing nothing but frontmatter and a header, do you still get the error?

**Comment by simplyeffectiveweb** [comment] 2015-09-25 15:15
The whole file (and there are only two), was originally this:

'---'
title: about
template: page.hbt
'---'

This is the about page

With ot without 'template' or the text, the same error occurs.

**Comment by Ajedi32** [comment] 2015-09-25 15:21
Okay, sounds like it might be a plugin, or maybe a problem with the metalsmith installation on your computer. Let's run the tests on your computer to see if Metalsmith is working. Try the following:

```bash
git clone https://github.com/segmentio/metalsmith.git
cd metalsmith
make test
```

If that works, then try:

```bash
cd examples/static-site
make build
```

**Comment by simplyeffectiveweb** [comment] 2015-09-25 15:32
It looks like metalsmith has changed more than i thought.

I was using a build.js and running the site with 'node build'

I don't have a command 'make'

I had a look at the examples and static-siite doesn't use a build.js or index.js, so I'm not sure what to do there.

At this stage perhaps I should accept defeat. I thought about returning to metalsmith rather than port the site to what I've been using since.

**Comment by Ajedi32** [comment] 2015-09-25 15:40
`make` is a standard Unix build tool. It's not really part of Metalsmith, and not necessary for Metalsmith projects; it's just there to make running tests easier. Also, you should still be able to use `node build.js` to execute a JavaScript script that calls Metalsmith's JavaScript API, the new Metalsmith CLI is just a convenience. But yes, there have been a lot of changes between versions 1.0 and 2.0 of Metalsmith.

I'm really surprised to hear you don't have make. It's pretty ubiquitous on Linux systems. Are you on Windows?

**Comment by simplyeffectiveweb** [comment] 2015-09-25 15:47
Yep, Windows 7 x64.

'node build' works, it's just that it gets stuck at that error. What's telling is that it's the same with all the projects (each using quite different plugins and approaches).

**Comment by Ajedi32** [comment] 2015-09-25 15:55
Okay, I think I might know what the problem is then. I can't be sure since I gave up trying to run Metalsmith on Windows as soon as I couldn't get the tests to pass (#158), but I think Metalsmith or one of its dependencies or plugins might be choking on the Windows-style line endings in your source files.

Do you have an editor that lets you see line endings? Notepad++ should work fine. (View -> Show Symbol -> Show All Characters). If that shows `CR` `LF` at the end of each line, that might be the problem. Clicking `Edit -> EOL Conversion -> UNIX Format` then saving the file might work.

**Comment by Ajedi32** [comment] 2015-09-25 15:59
Maybe in the future I'll do some work to try to get Metalsmith running smoothly on Windows. I would have done that sooner, but Windows tends to cause so many problems for me with open source projects that my default position has sort of become: "Doesn't work out-of-the-box for me on Windows? I'm just going to boot up a Linux VM and run it there." :wink:

**Comment by simplyeffectiveweb** [comment] 2015-09-25 16:48
Ok so that seems to be the issue. Doing the line end conversion removes the error. The site isn't building correctly (or as it was before). Not sure if that is some other issue or related to it being Windows.

Still it's good to know about metalsmith and Windows. I'd say there are still quite a lot of windows-based developers out there to make a fully ok Windows version worthwhile. Thanks very much for your time on this.

**Comment by simplyeffectiveweb** [comment] 2015-09-26 09:37
So with the line ending issue in mind, I discovered I could use 'Replace in Files' in Notepaddd++. So I did this in Windows:

1st   replaced  \r  with \r\n
2nd: replaced \n with \r\n
3rd: replaced \r\r\n with \r\n
4th: replaced \r\n\n with \r\n

(hope the reason for the 4 stage process is clear - some files had different line endings)

The result was that it worked, at least as far as I can see at ths stage.

**Comment by Ajedi32** [comment] 2015-09-27 01:57
Ah okay, good to hear you got it working. Still, Metalsmith should probably be more tolerant of Windows-style line endings. I'll look into that later when I try to get the tests passing on Windows.

**Comment by woodyrew** [comment] 2015-10-31 15:37
@simplyeffectiveweb: So, running Metalsmith on Windows, which of the following does it require?
1. `\n` - *nix
2. `\r\n` - Windows
3. `\r` - Mac

i.e. Does it require the native line ending according to the operating system?

**Comment by simplyeffectiveweb** [comment] 2015-10-31 21:42
Number 2 was what I changed the files to.

I don't know if that is native to the OS. I've never looked at line endings before.

There may be another reason that you and @Ajedi32 might want to test.  I had the same error with a diifferent application. The same line ending change process didn;t work that case. 

So after more research, I then started or restarted (I don't remember) the _Volume Shadow Copy_ service in Windows (7) and it worked.

**Comment by Ajedi32** [comment] 2015-10-31 22:22
Sounds like it needs native line endings.

Also, most versions of Mac actually use *nix style line endings. Only old versions use `\r`.

**Comment by woodyrew** [comment] 2015-10-31 22:36
That makes sense with it being based on FreeBSD.

**Comment by woodyrew** [comment] 2016-09-26 02:06
After looking into this a bit more, the issue arises where the line endings are not consistent with the operating system it is being run on.
This may be due to the (node core package) buffer expecting the native line ending.

**Closed** 2023-01-17 22:07 UTC
