### ISSUE TITLE
Make more explicit order matters in metalsmith.json

### ISSUE THREAD

**Issue by AdrieanKhisbe** [metalsmith/metalsmith#223] opened 2016-01-26 15:01 UTC
I end up discovereing debugging that order in metalsmith.json plugin declaration was important.

Would be usefull to mention it in a more explicit way. :smiley:

Cf: 
https://github.com/senecajs/senecajs.org/issues/168#issuecomment-175047730
https://github.com/senecajs/senecajs.org/commit/8768923ee65ee0b577c440be0437153559cacfb8

**Comment by Ajedi32** [comment] 2016-01-26 15:27
Well, the README and website do state that Metalsmith works by invoking a _series_ of plugins on the files, so we do kinda imply that order is important, but several people have had problems with this so I guess it's not obvious enough.

Would defining the plugins in an array instead of an object help?

I think part of the problem is that we just need more comprehensive documentation. The current official docs don't really have a whole lot of information on how to develop sites with Metalsmith.

**Comment by AdrieanKhisbe** [comment] 2016-01-26 15:34
Was pretty sure I overlooked it ;)
why i suggested to make it more obvious :smiley:

**Comment by fenwick67** [comment] 2016-08-10 03:00
Since object iteration order isn't technically guaranteed in JS, should the array syntax be preferred in the docs?

**Comment by Ajedi32** [comment] 2016-08-10 03:36
@fenwick67 Yes, I noticed that as well, and I agree. The array syntax should definitely be prefered.

**Comment by woodyrew** [comment] 2016-08-10 14:35
Array syntax should be the preferred method for sure. Examples defining plugins within an array, won't translate to everyone knowing that the order matters. We should explain why it's preferable to use an array IMO.

**Comment by Ajedi32** [comment] 2016-08-12 14:52
See also #129

**Comment by webketje** [comment] 2022-01-15 22:42
Closing as this has been altered in most plugins & on the website

**Closed by webketje** 2022-01-15 22:42 UTC
Labels: documentation, to revisit
