### ISSUE TITLE
Use declarative .json with javascript API

### ISSUE THREAD

**Issue by danigb** [metalsmith/metalsmith#128] opened 2015-04-06 20:35 UTC
Hello! First of all, awesome lib, thanks!

I want to use metalsmith within other js app, so I want to use the javascript API, but I like the declarative approach of the .json file.

I would love to be able to do something like this:

```
var config = require('./metalsmith.json);
var metalsmith = new Metalsmith(dir, config);
metalsmith.build(...);
```

That means, basically, move some logic from bin/metalsmith to lib/index.js 

What do you think? If you agree, I think I can make a pull request.

**Comment by ianstormtaylor** [comment] 2015-04-14 01:27
Sounds good to me! Seems like it would just be a few lines to change in the constructor. If you open a pull request I can comment and help merge!

**Comment by danigb** [comment] 2015-04-15 15:20
Great! I will work on the pull request. 

What I imagine is moving quite a lot of code from bin/metalsmith to ./index.js: from line 68 to 104 and the normalize method. What do you think?

Also, regarding to that last method, I would like to change the name to something less abstract. Any ideas?

**Comment by ianstormtaylor** [comment] 2015-04-15 16:59
Nice. I see it more as cleaning up lines [67–72](https://github.com/segmentio/metalsmith/blob/master/bin/metalsmith#L67-L72), and not as much the stuff that's normalizing and resolving plugins from the `metalsmith.json` file. That resolving logic particularly is very specific to the `metalsmith.json`, which is only a convenience for the CLI. Similarly the idea of handling arrays (the purpose for `normalize`) is only needed in the CLI, since with the JS API order is implied by the order they are added already.

**Comment by danigb** [comment] 2015-04-15 19:28
Yes, I suspected there were some kind of misunderstanding here. I'm not native english, so probably I didn't explain very well...

Let me elaborate my use case: we're building a web application that, as a result of an action, some kind of "build" is done, and we're using metalsmith for that. Since we need to use it within our app, the JS API is the straight option, but I really like the metalsmith.json style (it's more declarative and clear, easy to follow for long configurations). 
So we ended coping and paste'ing some code from the CLI in order to keep the metalsmith.json file and use it withing our app action.

So I think maybe its a good idea to move the configuration stuff of the client inside metalsmith itself (but maybe it's not a good idea, thats why I opened this issue and discuss it).
Also, we made some changes to the CLI code in order to call the same plugin twice with different options. Thats why I opened issue #129 

What do you think?

Thanks in advance.

**Comment by ianstormtaylor** [comment] 2015-04-15 19:46
Ah gotcha. At that point you could just use the CLI via `child_process.exec` if you wanted? I'm just a bit skeptical about having all of the `process.cwd`-specific stuff that tries to resolve `node_modules` live inside the core Javascript API itself, since it seems unrelated to trying to do things easily with Javascript, and is more about sugar required from having to declare metadata in JSON.

**Comment by danigb** [comment] 2015-04-15 19:55
Yes, I agree with all about the sugar code (I really like the minimalistic design of metalsmith). We'll find another option (yes, maybe `child_process.exec`). Probably we should close this issue and #129.

**Comment by ianstormtaylor** [comment] 2015-04-15 20:02
Sounds good, I'll close this one. The other would be good to actually document so I'll leave it open for now

**Comment by jmatsushita** [comment] 2016-04-01 05:14
I thought I'd revive this old issue rather than opening a new one since I ran into the same need for almost the same reasons.

I want to programmatically launch metalsmith and have some elements of the plugin config be dynamically modified but want to use the declarative .json file for the core of the build pipe (merging the dynamic plugin with the json config).

Spawning metalsmith via the CLI would mean also being able to pass the merged config to the the spawned process which is not trivial (unless writing a temp config file to disk and spawning metalsmith with arguments which is a bit of a dirty workaround.

Stepping back though, there might be a better way to achieve what I want (slightly off-topic) which is to tell the build pipeline to ignore some plugins based on CLI arguments (or environment variables). Specifically reproduce the `jekyll build` `jekyll serve` `jekyll serve --watch` trio and extend it with more options.

**Comment by Ajedi32** [comment] 2016-04-01 13:24
Sounds reasonable to me. Basically all we'd have to do would be extract the code in `bin/_metalsmith` to it's own module and expose it to the end user.

**Comment by webketje** [comment] 2023-06-05 23:33
I think with release 2.6.0 there's enough flexibility in overriding configs and added flexibility in the config formats.

**Closed by webketje** 2023-06-05 23:33 UTC
Labels: feature, pull request appreciated, hacktoberfest
